// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wheelzy.Infrastructure.Persistence;

#nullable disable

namespace Wheelzy.Infrastructure.Migrations
{
    [DbContext(typeof(WheetzyDbContext))]
    partial class WheetzyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wheelzy.Application.Models.Buyer", b =>
                {
                    b.Property<int>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BuyerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Buyer", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.BuyerZipCoverage", b =>
                {
                    b.Property<int>("BuyerZipCoverageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuyerZipCoverageId"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DefaultQuoteAmount")
                        .HasColumnType("money");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.HasKey("BuyerZipCoverageId");

                    b.HasIndex("ZipCode")
                        .HasDatabaseName("IX_BuyerZipCoverage_Zip");

                    b.HasIndex("BuyerId", "ZipCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Buyer_Zip");

                    b.ToTable("BuyerZipCoverage", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("SubmodelId")
                        .HasColumnType("int");

                    b.Property<short>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("CarId");

                    b.HasIndex("SubmodelId")
                        .HasDatabaseName("IX_Car_SubmodelId");

                    b.ToTable("Car", null, t =>
                        {
                            t.HasCheckConstraint("CK_Car_YearRange", "[Year] >= 1900 AND [Year] <= 2100");
                        });
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarMake", b =>
                {
                    b.Property<int>("MakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MakeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MakeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CarMake", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("MakeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModelId");

                    b.HasIndex("MakeId")
                        .HasDatabaseName("IX_CarModel_MakeId");

                    b.HasIndex("MakeId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_CarModel");

                    b.ToTable("CarModel", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarSubmodel", b =>
                {
                    b.Property<int>("SubmodelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmodelId"));

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubmodelId");

                    b.HasIndex("ModelId")
                        .HasDatabaseName("IX_CarSubmodel_ModelId");

                    b.HasIndex("ModelId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_CarSubmodel");

                    b.ToTable("CarSubmodel", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .IsFixedLength();

                    b.HasKey("CustomerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ZipCode");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CustomerCar", b =>
                {
                    b.Property<int>("CustomerCarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerCarId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CustomerCarId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerCars", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasDefaultValue("USD");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Invoice_OrderId");

                    b.HasIndex("CustomerId", "IssuedAt")
                        .HasDatabaseName("IX_Invoice_CustomerId_IssuedAt");

                    b.ToTable("Invoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_PaidDate", "([IsPaid]=(0) AND [PaidAt] IS NULL) OR ([IsPaid]=(1) AND [PaidAt] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int?>("CurrentOrderBuyerQuoteId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentStatusChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CurrentStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("CurrentStatusId")
                        .HasDatabaseName("IX_Order_CurrentStatusId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ZipCode");

                    b.HasIndex("CurrentOrderBuyerQuoteId", "OrderId")
                        .HasDatabaseName("IX_Order_CurrentOrderBuyerQuoteId");

                    b.ToTable("Order", null, t =>
                        {
                            t.HasCheckConstraint("CK_Order_PickedUpDate", "([CurrentStatusId] IS NULL OR [CurrentStatusId] <> 3 OR [CurrentStatusDate] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Wheelzy.Application.Models.OrderBuyerQuote", b =>
                {
                    b.Property<int>("OrderBuyerQuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderBuyerQuoteId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("money");

                    b.Property<int>("BuyerZipCoverageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("OrderBuyerQuoteId");

                    b.HasIndex("BuyerZipCoverageId");

                    b.HasIndex("OrderBuyerQuoteId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrderBuyerQuote_Id_OrderId");

                    b.HasIndex("OrderId", "BuyerZipCoverageId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Quote_Per_Case_Buyer");

                    b.ToTable("OrderBuyerQuote", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StatusId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderStatus", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusHistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("OrderStatusHistoryId");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderStatusHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaseStatusHistory_PickedUpDate", "([StatusId] <> 3 OR [StatusDate] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Wheelzy.Application.Models.ZipCode", b =>
                {
                    b.Property<string>("ZipCodeId")
                        .HasColumnType("char(5)")
                        .HasColumnName("ZipCode");

                    b.HasKey("ZipCodeId");

                    b.ToTable("ZipCode", (string)null);
                });

            modelBuilder.Entity("Wheelzy.Application.Models.BuyerZipCoverage", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.Buyer", "Buyer")
                        .WithMany("BuyerZipCoverages")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.ZipCode", "Zip")
                        .WithMany("BuyerCoverages")
                        .HasForeignKey("ZipCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Car", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.CarSubmodel", "Submodel")
                        .WithMany("Cars")
                        .HasForeignKey("SubmodelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submodel");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarModel", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.CarMake", "Make")
                        .WithMany("Models")
                        .HasForeignKey("MakeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Make");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarSubmodel", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.CarModel", "Model")
                        .WithMany("Submodels")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Customer", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.ZipCode", "ZipCodeRef")
                        .WithMany("Customers")
                        .HasForeignKey("ZipCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ZipCodeRef");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CustomerCar", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.Car", "Car")
                        .WithMany("CustomerCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.Customer", "Customer")
                        .WithMany("CustomerCars")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Invoice", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Order", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.OrderBuyerQuote", "CurrentOrderBuyerQuote")
                        .WithMany()
                        .HasForeignKey("CurrentOrderBuyerQuoteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Wheelzy.Application.Models.OrderStatus", "CurrentStatus")
                        .WithMany("CurrentOrders")
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wheelzy.Application.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.ZipCode", "Zip")
                        .WithMany("Orders")
                        .HasForeignKey("ZipCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CurrentOrderBuyerQuote");

                    b.Navigation("CurrentStatus");

                    b.Navigation("Customer");

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.OrderBuyerQuote", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.BuyerZipCoverage", "BuyerZipCoverage")
                        .WithMany("OrderBuyerQuotes")
                        .HasForeignKey("BuyerZipCoverageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.Order", "Order")
                        .WithMany("OrderBuyerQuotes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BuyerZipCoverage");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("Wheelzy.Application.Models.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wheelzy.Application.Models.OrderStatus", "Status")
                        .WithMany("Histories")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Buyer", b =>
                {
                    b.Navigation("BuyerZipCoverages");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.BuyerZipCoverage", b =>
                {
                    b.Navigation("OrderBuyerQuotes");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Car", b =>
                {
                    b.Navigation("CustomerCars");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarMake", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarModel", b =>
                {
                    b.Navigation("Submodels");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.CarSubmodel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Customer", b =>
                {
                    b.Navigation("CustomerCars");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderBuyerQuotes");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.OrderStatus", b =>
                {
                    b.Navigation("CurrentOrders");

                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Wheelzy.Application.Models.ZipCode", b =>
                {
                    b.Navigation("BuyerCoverages");

                    b.Navigation("Customers");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
