namespace Wheelzy.Domain;

public class Make { public int MakeId { get; set; } public string Name { get; set; } = null!; public ICollection<Model> Models { get; set; } = new List<Model>(); }
public class Model { public int ModelId { get; set; } public int MakeId { get; set; } public string Name { get; set; } = null!; public Make? Make { get; set; } public ICollection<Submodel> Submodels { get; set; } = new List<Submodel>(); }
public class Submodel { public int SubmodelId { get; set; } public int ModelId { get; set; } public string Name { get; set; } = null!; public Model? Model { get; set; } }
public class ZipCode { public string ZipCodeId { get; set; } = null!; }
public class Customer { public int CustomerId { get; set; } public string FullName { get; set; } = null!; public string? Email { get; set; } }
public class Buyer { public int BuyerId { get; set; } public string Name { get; set; } = null!; public ICollection<BuyerZipQuote> BuyerZipQuotes { get; set; } = new List<BuyerZipQuote>(); }
public class BuyerZipQuote { public int BuyerId { get; set; } public string ZipCodeId { get; set; } = null!; public decimal Amount { get; set; } public Buyer? Buyer { get; set; } public ZipCode? ZipCode { get; set; } }
public class CarCase { public int CaseId { get; set; } public int CustomerId { get; set; } public short Year { get; set; } public int MakeId { get; set; } public int ModelId { get; set; } public int? SubmodelId { get; set; } public string ZipCodeId { get; set; } = null!; public Customer? Customer { get; set; } public Make? Make { get; set; } public Model? Model { get; set; } public Submodel? Submodel { get; set; } public ZipCode? ZipCode { get; set; } public ICollection<CaseQuote> Quotes { get; set; } = new List<CaseQuote>(); public ICollection<CaseStatus> Statuses { get; set; } = new List<CaseStatus>(); }
public class CaseQuote { public long CaseQuoteId { get; set; } public int CaseId { get; set; } public int BuyerId { get; set; } public decimal Amount { get; set; } public bool IsCurrent { get; set; } public CarCase? Case { get; set; } public Buyer? Buyer { get; set; } }
public class Status { public int StatusId { get; set; } public string Name { get; set; } = null!; public string Code { get; set; } = null!; }
public class CaseStatus { public long CaseStatusId { get; set; } public int CaseId { get; set; } public int StatusId { get; set; } public DateTime? StatusDate { get; set; } public string? ChangedBy { get; set; } public bool IsCurrent { get; set; } public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; public CarCase? Case { get; set; } public Status? Status { get; set; } }
