<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOs\Buyer\**" />
    <EmbeddedResource Remove="DTOs\Buyer\**" />
    <None Remove="DTOs\Buyer\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\Profiles\" />
    <Folder Include="Mapping\Registration\" />
  </ItemGroup>

</Project>
